leftnav:
- identifier: b26e8275-02d7-4839-8b22-129fccaeaff6
  name: Online Publication
  pageRef: /external-resources/online-publication_b26e8275-02d7-4839-8b22-129fccaeaff6
  weight: 10
- identifier: 25b6e238-e8fe-44be-8883-0da3521015fa
  name: A Learner's Guide
  pageRef: /external-resources/a-learners-guide_25b6e238-e8fe-44be-8883-0da3521015fa
  weight: 20
